### PR TITLE
fix(notifier): prevent marking emoji as 'known' on LLM or Slack message failure

### PR DESCRIPTION
**Pull request by DAcodedBEAT**
This PR improves the handling of the `n.eventsMutex` in the `handleNewEmoji` method and adds error recovery for generating sentences and sending messages.

## What? (description)

- Used `defer` to ensure `n.eventsMutex.Unlock()` is always called, preventing potential deadlocks.
- Added logic to reset `n.knownEmojis[name]` to `false` if:
  - Generating a sentence fails.
  - Sending a message to Slack fails.

## Why? (reasoning)

- **Mutex Safety**: Ensures the mutex is always released properly.
- **Error Handling**: Allows reprocessing of emojis if an error occurs, improving reliability.

### CODE REVIEW

**Comment by DAcodedBEAT** [comment]
@particledecay can you review and merge?

**Review by particledecay — APPROVED** [review]

**Comment by particledecay** [comment]
@DAcodedBEAT hey just make sure the tests pass, looks like some secrets allowlisting

I'll have to remove the codeclimate one so ignore that for now

**Comment by DAcodedBEAT** [comment]
> @DAcodedBEAT hey just make sure the tests pass, looks like some secrets allowlisting
> 
> I'll have to remove the codeclimate one so ignore that for now

@particledecay Not sure how to proceed here, the output says the secrets is sourced from the README.md, according to. https://github.com/particledecay/slackmoji-notifier/actions/runs/11524873863/job/32085969701?pr=2#step:6:105

I did not touch this file and it looks like it's complaining about `--set openai.apiKey="your-openai-api-key"` (https://github.com/particledecay/slackmoji-notifier/blob/main/README.md?plain=1#L40)

**Comment by DAcodedBEAT** [comment]
Looking further, it looks like https://github.com/particledecay/slackmoji-notifier/blob/main/.github/workflows/tests.yml was only ran on my PRs and not any of the other pushes to the repository (https://github.com/particledecay/slackmoji-notifier/actions/workflows/tests.yml) - this is definitely unrelated to my changes.

**Comment by particledecay** [comment]
@DAcodedBEAT can you rebase your branch with the latest please? Hopefully all should be good now.

**Comment by DAcodedBEAT** [comment]
@particledecay it looks like this is still reporting the same detect-secrets issue, is the exclude regex correct?

from https://github.com/Yelp/detect-secrets, `If lines match this regex, it will be ignored.`

**Comment by particledecay** [comment]
@DAcodedBEAT you're right, it was wrong... I just pushed a fix. Can you rebase and try again?

**Comment by DAcodedBEAT** [comment]
Heck yeah! Finally a green check ✅ !

This looks good to go @particledecay 

Once this gets merged, I will rebase the other PR too

**Pull request merged**
